Fix --fixture-graph-output-dir and --fixture-graph-output-type
Command line options `--fixture-graph-output-dir` and `--fixture-graph-output-type` wouldn't allow you to actually pass custom value, since their action was to store a boolean:

```
$ pytest  --fixture-graph --fixture-graph-output-type=pdf
ERROR: usage: pytest [options] [file_or_dir] [file_or_dir] [...]
pytest: error: argument --fixture-graph-output-type: ignored explicit argument 'pdf'

$ pytest  --fixture-graph --fixture-graph-output-dir=./foo
ERROR: usage: pytest [options] [file_or_dir] [file_or_dir] [...]
pytest: error: argument --fixture-graph-output-dir: ignored explicit argument './foo'
```